### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by timlaw71** [m8sec/pymeta#20]
I'm getting this error when trying to run.

└─$ pymeta -h             
Traceback (most recent call last):
  File "/usr/local/bin/pymeta", line 33, in <module>
    sys.exit(load_entry_point('pymetasec==1.2.0', 'console_scripts', 'pymeta')())
  File "/usr/local/bin/pymeta", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/tim/.local/lib/python3.10/site-packages/pymeta/__init__.py", line 140
    def get_agent():
                    ^
IndentationError: unindent does not match any outer indentation level

**Comment by m8sec** [comment]
Hi @timlaw71,

I have not yet tested PyMeta with Python 3.10 and will absolutely look into this. Does it work with lower versions of the language?

**Comment by timlaw71** [comment]
If I run python3 ./pymeta.py if seems to work. I'm on python 3.10.8

**Comment by Anzo52** [comment]
I have this fixed if you'd like me to open a PR.

**Comment by Draoken** [comment]
> I had the same error on Python 3.9, downloaded from pypi. In the package I just went to line 140 in ./env/lib/Python3.9/site-packages/pymeta/**init**.py and fixed the indent on "def get_agent():" and it worked.

Would like to add I had the same issue, and same thing fixed it. There is a space or two in front of the line "def get_agent()".
